//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningMauiBankingApp.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_pl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_pl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LearningMauiBankingApp.Localization.Strings.pl", typeof(Strings_pl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ConnectivityAlert_ButtonText {
            get {
                return ResourceManager.GetString("ConnectivityAlert_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet powrócił. Dobra robota!.
        /// </summary>
        internal static string ConnectivityAlert_InternetOkMessage {
            get {
                return ResourceManager.GetString("ConnectivityAlert_InternetOkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Połączenie z internetem wznowione.
        /// </summary>
        internal static string ConnectivityAlert_InternetOkTitle {
            get {
                return ResourceManager.GetString("ConnectivityAlert_InternetOkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proszę upewnić sie że urządzenie ma dostęp do sieci internet.
        /// </summary>
        internal static string ConnectivityAlert_NoInternetMessage {
            get {
                return ResourceManager.GetString("ConnectivityAlert_NoInternetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak połączenia z internetem.
        /// </summary>
        internal static string ConnectivityAlert_NoInternetTitle {
            get {
                return ResourceManager.GetString("ConnectivityAlert_NoInternetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bankomaty.
        /// </summary>
        internal static string HomePage_AtmButton {
            get {
                return ResourceManager.GetString("HomePage_AtmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ładowanie....
        /// </summary>
        internal static string HomePage_CardsLoading {
            get {
                return ResourceManager.GetString("HomePage_CardsLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashback.
        /// </summary>
        internal static string HomePage_CashbackButton {
            get {
                return ResourceManager.GetString("HomePage_CashbackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pożyczki.
        /// </summary>
        internal static string HomePage_CreditsButton {
            get {
                return ResourceManager.GetString("HomePage_CreditsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokaty.
        /// </summary>
        internal static string HomePage_DepositsButton {
            get {
                return ResourceManager.GetString("HomePage_DepositsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kantor.
        /// </summary>
        internal static string HomePage_ExchangeButton {
            get {
                return ResourceManager.GetString("HomePage_ExchangeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inne.
        /// </summary>
        internal static string HomePage_MoreButton {
            get {
                return ResourceManager.GetString("HomePage_MoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments.
        /// </summary>
        internal static string HomePage_PaymentsButton {
            get {
                return ResourceManager.GetString("HomePage_PaymentsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezpieczeństwo.
        /// </summary>
        internal static string HomePage_SecurityButton {
            get {
                return ResourceManager.GetString("HomePage_SecurityButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przelew.
        /// </summary>
        internal static string HomePage_TransferButton {
            get {
                return ResourceManager.GetString("HomePage_TransferButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj się.
        /// </summary>
        internal static string LoginPage_LoginButton {
            get {
                return ResourceManager.GetString("LoginPage_LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        internal static string LoginPage_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("LoginPage_PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa użytkownika.
        /// </summary>
        internal static string LoginPage_UsernamePlaceholder {
            get {
                return ResourceManager.GetString("LoginPage_UsernamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witaj.
        /// </summary>
        internal static string LoginPage_Welcome {
            get {
                return ResourceManager.GetString("LoginPage_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień motyw.
        /// </summary>
        internal static string SettingsPage_SwitchThemeButton {
            get {
                return ResourceManager.GetString("SettingsPage_SwitchThemeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przełącz na Angielski.
        /// </summary>
        internal static string SettingsPage_SwitchToEnglishButton {
            get {
                return ResourceManager.GetString("SettingsPage_SwitchToEnglishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przełącz na Polski.
        /// </summary>
        internal static string SettingsPage_SwitchToPolishButton {
            get {
                return ResourceManager.GetString("SettingsPage_SwitchToPolishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia.
        /// </summary>
        internal static string SettingsPage_Title {
            get {
                return ResourceManager.GetString("SettingsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z karty.
        /// </summary>
        internal static string TransferPage_FromCardPicker {
            get {
                return ResourceManager.GetString("TransferPage_FromCardPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wewnętrzny przelew.
        /// </summary>
        internal static string TransferPage_Title {
            get {
                return ResourceManager.GetString("TransferPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na kartę.
        /// </summary>
        internal static string TransferPage_ToCardPicker {
            get {
                return ResourceManager.GetString("TransferPage_ToCardPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykonać.
        /// </summary>
        internal static string TransferPage_TransferButton {
            get {
                return ResourceManager.GetString("TransferPage_TransferButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witam z powrotem, .
        /// </summary>
        internal static string TTS_WelcomeBack {
            get {
                return ResourceManager.GetString("TTS_WelcomeBack", resourceCulture);
            }
        }
    }
}
